categories:
  SitePackage:
    label: 'Site Package'
  SitePackage.templates:
    label: 'Templates'
    parent: SitePackage
  SitePackage.layout:
    label: 'Layout'
    parent: SitePackage
  SitePackage.menus:
    label: 'Menus'
    parent: SitePackage

settings:
  SitePackage.template_path:
    label: 'Page template path'
    category: SitePackage.templates
    description: 'Path to the templates of the Site Package.'
    type: string
    default: 'EXT:site_package/Resources/Private/Templates/'

  SitePackage.logo:
    label: 'Logo'
    category: SitePackage.layout
    description: 'Path to the logo of Site Package.'
    type: string
    default: 'EXT:site_package/Resources/Public/Images/logo.svg'

  SitePackage.logo-alt:
    label: 'Logo Alt text'
    category: SitePackage.layout
    description: 'Alternative text of the logo for the visually impaired'
    type: string
    default: 'Logo'

  SitePackage.favicon:
    label: 'Favicon'
    description: 'This icon is displayed in search engine results and in the browser tab'
    category: SitePackage.layout
    type: string
    default: 'EXT:site_package/Resources/Public/Icons/favicon.ico'

  SitePackage.footerMenuRoot:
      label: 'Footer menu root uid'
      description: 'The subpages of this page are displayed in the footer'
      category: SitePackage.menus
      type: int
      default: 2
